### ISSUE TITLE
Plans on migrating to use multiformats

### ISSUE THREAD

**Issue by alvin-reyes** [ipfs/ipld-explorer-components#311]
Hello Maintainers,

I'm trying to extend the ipld-explorer-components to add support to explore CAR and I noticed that the following modules are now deprecated.

```
"cids"
"multibase"
"multicodec"
"multihashes"
```

It is superseded by the `multiformats` module: https://www.npmjs.com/package/multiformats. 

Question, are there any plans to upgrade? I figured since I'm extending the explorer, I might as well upgrade the module.

Thank you.

**Comment by lidel** [comment]
_:cricket:  (there are no maintainers nor plans)_

@alvin-reyes  If you have time to do the refactor and the update, I can help with reviewing and merging.
Main caveat is that this component is used in both https://github.com/ipld/explore.ipld.io and  https://github.com/ipfs/ipfs-webui and has to work in both places.

**Comment by lidel** [comment]
Update:
- https://github.com/ipfs/ipld-explorer-components/pull/313 added https://www.npmjs.com/package/multiformats as dependency but it is only used during CAR import – everything else remains untouched.
- Refactoring old code to use modern `multiformats` libraries and codecs is something that can be tackled independently, eg. as part of https://github.com/ipfs/ipfs-webui/issues/1923

**Comment by rvagg** [comment]
Worth noting that this switch is going to introduce problems for the Ethereum and Git examples in the explore since we don't have updated codecs for these. I have a Bitcoin codec that is half-way there (there was an intermeditate `@ipld/block` that came before `multiformats` as an experiment in next-gen JS IPLD that it was based on, I haven't quite upgraded it yet, it's a bit complex and has been a very low priority). We could also probably make adapters for the existing codecs if they're important, or perhaps we decide that they are important enough to properly port and just get it done—it's really a matter of prioritisation. Alternatively we ditch the bespoke codecs from the list, and maybe add other interesting examples, maybe even a dag-jose block which is now supported down through go-ipfs and js-ipfs.

**Comment by SgtPooki** [comment]
I think the first step is defining migration steps. e.g. what are the migration steps for 
https://github.com/ipfs/ipld-explorer-components/blob/16508c169abf0a062df822f784cf8769ead848b0/src/lib/normalize-dag-node.test.js#L2-L3
and https://github.com/ipfs/ipld-explorer-components/blob/master/src/lib/resolve-ipld-path.test.js#L2-L10 ?

There are a large number of dependents for all of these deprecated packages:

https://www.npmjs.com/browse/depended/cids
https://www.npmjs.com/browse/depended/multibase
https://www.npmjs.com/browse/depended/multicodec
https://www.npmjs.com/browse/depended/multihashes

and each dependent may be using them differently.. we need to dive into it to figure out what we need to support

**Comment by SgtPooki** [comment]
This should be fixed when #359 is resolved
