### ISSUE TITLE
Unable to traverse inside of a chunked file

### ISSUE THREAD

**Issue by lidel** [ipfs/ipld-explorer-components#461]
**Describe the bug**

Walking into a file makes it impossible to navigate further due to no path label to click.

**To Reproduce**

1. Go to  https://explore.ipld.io/#/explore/QmSnuWmxptJZdLJpKRarxBMS2Ju2oANVrgbr2xWbie9b2D/albums/QXBvbGxvIDE0IE1hZ2F6aW5lIDY0L0xM/21076550124_dfaa21d664_o.jpg (Apollo Archives Example)
2. Click on  any chunk, eg. 0 or 1
4. See that nothing happens, only a breadcrumb is added, but navigation does not happen

**Expected behavior**

Clicking on a node without Path should still work, and navigate to respective child chunk. 

**Screenshots**

> ![2024-11-09_02-07](https://github.com/user-attachments/assets/062cde74-fb5f-4b01-80f2-88f3f29cec9b)

**Additional context**

- This happens in https://github.com/ipfs/ipfs-webui/releases/tag/v4.4.0 as well (http://127.0.0.1:5001/ipfs/bafybeibgic2ex3fvzkinhy6k6aqyv3zy2o7bkbsmrzvzka24xetv7eeadm/#/explore/QmSnuWmxptJZdLJpKRarxBMS2Ju2oANVrgbr2xWbie9b2D/albums/QXBvbGxvIDE0IE1hZ2F6aW5lIDY0L0xM/21076550124_dfaa21d664_o.jpg)
- I think in the past we avoided this bug by creating "fake path" labels named "Link-1"  or something like that, maybe we should just reuse CID?
- Sidenote: I vaguely remember that in past we've discussed avoiding infinite breadcrumbs growing too long, and had idea to only keep last 2 parents.

**Comment by SgtPooki** [comment]
The actual bug is here: https://github.com/ipfs/ipld-explorer-components/blob/b37f7c0dc84e4a447d3fd0bd64c16ac1daa39e55/src/lib/normalise-dag-node.ts#L96

This was another part of updating to the latest aegir.. basically we were previously doing `foo || other thing` that was triggering if the first var was an empty string, but we're now doing the more idiomatic `foo ?? other thing`.

<img width="235" alt="image" src="https://github.com/user-attachments/assets/9ef249cf-f27b-482c-849a-82913009340f">

The helper function to use in this case is https://github.com/ipfs/ipld-explorer-components/blob/b37f7c0dc84e4a447d3fd0bd64c16ac1daa39e55/src/lib/helpers.ts#L11-L24
